apiVersion: stork.libopenstorage.org/v1alpha1
kind: MigrationSchedule
metadata:
  name: failovermigrationschedule
  namespace: test-async-dr
spec:
  template:
    spec:
      clusterPair: remote-us-east-cluster
      includeResources: true
      includeVolumes: true
      startApplications: true # set to false for complex applications where changes would be needed before starting the app on disaster site
      namespaces:
      - pb-pwx-test
  schedulePolicyName: failoverschedulepolicy